Přidání enumeračních (výčtových) konstant
vyfakturuj/vyfakturuj-api-php pull request #6
Opened 2018-08-31 05:25 UTC by jakubboucek

> Toto závisí na #5 - nejdřív se musí mergnout ta

V kódu i v příkladech se pracuje pouze číselnou interpretací různých přepínačů.

BC: ne

Doplnil jsem sadu konstant, které odpovídají hodnotám v [dokumentaci](https://vyfakturujcz.docs.apiary.io/#) a upravil jsem příklady.

Původní zápis:
```php
$opt = array(
    'type' => 1,
    'calculate_vat' => 2,
    'payment_method' => 2
);
```

Nový zápis:
```php
$opt = array(
    'type' => VyfakturujEnum::DOCUMENT_TYPE_FAKTURA,
    'calculate_vat' => VyfakturujEnum::VAT_CALC_METHOD_AMOUNT_WITH_VAT,
    'payment_method' => VyfakturujEnum::PAYMENT_METHOD_CASH
);
```

Názvy konstant jsou většinou převzaty ze zdrojového kódu Vyfakturuj, ale nejsou 1:1 (drobné úpravy, stylystické i gramatické korekce).

2018-08-31 12:36 UTC, Dosty85 requested changes
Viz rozhovor po skype

2018-08-31 15:11 UTC, jakubboucek commented
Doplním důvod zamítnutí pro archivaci:
Nový zápis pomocí konstant může být vhodný pro programátory, naopak může děsit začátečníky – což je ovšem cílovka Vyfakturuj. 

Upravit tak, aby konstanty byla volba, nikoliv hlavní cesta.

2018-08-31 15:25 UTC, jakubboucek commented
Návrh nové textace:
```
Některá čísla v příkladu níže jsou číselná označení systémových typů.
Například: 'type' => 1 znamená, že vytvořený doklad bude Faktura a nikoliv třeba Výzva k platbě.
Popis všech hodnot najdete v dokumentaci: https://vyfakturujcz.docs.apiary.io/#reference/faktury
Zkušenější uživatelé mohou použít výčet možných hodnot v přiložené třídě VyfakturujEnum.
``` 

Screenshot:
![image](https://user-images.githubusercontent.com/1657322/44921343-a277b100-ad42-11e8-854c-6e4a2f0edfd0.png)

2018-09-01 06:14 UTC, jakubboucek commented
Upraveno, odsouhlaseno přes Hangouts, merguju.

2018-09-01 06:16 UTC, merged